### ISSUE TITLE
Not sync data and articles

### ISSUE THREAD

**Issue by arlido** [nodew/PocketDesktop#38]
Version installed from MS Store (2.0.1.0) not sync any data. App is empty (no articles show). Only circle animation "do job" round in loop, but nothing happened.

**Comment by unliftedq** [comment]
Can you have a try on the settings page to manually sync data?

**Comment by arlido** [comment]
Yes I try to do that, but there is no button there. Only circle spin around. It looks like try to sync data, but nothing happen. When I restart app sync start immediately after I strat it. I try to restart app, reinstall it, but this things don't help.

**Comment by unliftedq** [comment]
Just have a quick check, the retrieve call to getpocket throws exception, which lead to the sync failure, will make a hotfix asap.

**Comment by unliftedq** [comment]
@arlido The fixed version is deployed, please upgrade and have a try.
